-- Active: 1791293626063@@127.0.0.1@3306

USE prototype;

CREATE TABLE IF NOT EXISTS Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(20) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Profiles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    User_id INT(255),
    Dark_Mode BOOL,
    Created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
