services:

  web:
    build: .
    container_name: Database
    ports:
      - "5001:5000"
    environment:
      DB_HOST: db
      DB_USER: flaskuser
      DB_PASSWORD: flaskpass
      DB_NAME: prototype
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:11.8
    container_name: user_database
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpass123
      MARIADB_DATABASE: prototype
      MARIADB_USER: flaskuser
      MARIADB_PASSWORD: flaskpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
